- iac-common/src/main/java/org/sonar/iac/common/extension/IacSensor.java
- iac-common/src/main/java/org/sonar/iac/common/testing/AbstractSensorTest.java
- iac-common/src/test/java/org/sonar/iac/common/extension/IacSensorTest.java
- iac-extensions/cloudformation/src/main/java/org/sonar/iac/cloudformation/plugin/CloudformationSensor.java
- iac-extensions/cloudformation/src/test/java/org/sonar/iac/cloudformation/plugin/CloudformationSensorTest.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/plugin/TerraformSensor.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/plugin/TerraformSensorTest.java
This pull request is inspired by https://github.com/SonarSource/sonar-swift/pull/429 which was given as an example during the weekly.
> SONARIAC-283 Declare CloudFormation and Terraform sensor as a sensor processing files independently

- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6375.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6378.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6379.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6380.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6381.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6382.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6383.json
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6387.json
This reverts commit a60f7ecab6ec3d29c9a7709ccdfbc85ad7a0fbe5.
> Revert "Change rule type to CODE_SMELL for evaluation purpose (#267)"

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/AzureClearTextProtocolsCheckPart.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/ClearTextProtocolsCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_spring_cloud_app.tf
azurerm_spring_cloud_app.https_only ClearTextProtocolsCheck
> SONARIAC-295

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/AzureClearTextProtocolsCheckPart.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/ClearTextProtocolsCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_function_app.tf
azurerm_function_app clear text protocols check implemented
> SONARIAC-298

- iac-common/src/main/java/org/sonar/iac/common/checks/TextUtils.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/AbstractResourceCheck.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/AzureClearTextProtocolsCheckPart.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/ClearTextProtocolsCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_app_service.tf
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_cdn_endpoint.tf
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_redis_enterprise_database.tf
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_xyzsql_server.tf
- its/ruling/src/test/resources/expected/terraform/terraform-S5332.json
- its/ruling/src/test/resources/expected/terraform/terraform-S6321.json
implement SONARIAC-296, 300, 301
> SONARIAC-300

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/AbstractResourceCheck.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/ResourceVisitor.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/AzureClearTextProtocolsCheckPart.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/HigherPrivilegedRoleAssignmentCheck.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/utils/TerraformUtils.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/ClearTextProtocolsCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/ClearTextProtocolsCheck/azurerm_api_management_api.tf
Check if terraform module azurerm_api_management_api allows HTTP
> SONARIAC-299

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/UnencryptedCloudServicesCheck.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/UnencryptedCloudServicesCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/UnencryptedCloudServicesCheck/azurerm_windows_virtual_machine_scale_set.tf
- its/ruling/src/test/resources/expected/terraform/terraform-S6388.json
Encryption for Windows VM Scale Set
> SONARIAC-306

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/visitors/TerraformHighlightingVisitor.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/visitors/TerraformHighlighterVisitorTest.java
Please see the [Jira](https://jira.sonarsource.com/browse/SONARIAC-370) ticket to see a before-after example.
> SONARIAC-370 Update Terraform syntax highlighting

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/gcp/HighPrivilegedRolesOnIamResourcesCheckPart.java
- iac-extensions/terraform/src/test/resources/checks/GCP/AdministrativeRolesOnWorkloadResourcesCheck/role_assignment.tf
The correct messages were specified in a comment to SONARIAC-361
> use correct messages when reporting S6400

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/PublicNetworkAccessCheck.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/AzurePublicNetworkAccessCheckPart.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/gcp/GcpPublicNetworkAccessCheckPart.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/BlockSymbol.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/ResourceSymbol.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/Symbol.java
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6329.html
- iac-extensions/terraform/src/main/resources/org/sonar/l10n/terraform/rules/terraform/S6329.json
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/PublicNetworkAccessCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/PublicNetworkAccessCheck/gcp_cloudbuild_worker_pool.tf
- iac-extensions/terraform/src/test/resources/checks/PublicNetworkAccessCheck/gcp_compute_instance.tf
- iac-extensions/terraform/src/test/resources/checks/PublicNetworkAccessCheck/gcp_notebooks_instance.tf
- iac-extensions/terraform/src/test/resources/checks/PublicNetworkAccessCheck/gcp_sql_database_instance.tf
- its/ruling/src/test/resources/expected/terraform/terraform-S6329.json
This PR combines all implementations of the sub-tasks of SONARIAC-325.
> SONARIAC-325 Rule S6329: Allowing public network access to cloud resources is security-sensitive (GCP)

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/DisabledLoggingCheck.java
- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/aws/AzureDisabledLoggingCheckPart.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/DisabledLoggingCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/DisabledLoggingCheck/azurerm_app_service.tf
- iac-extensions/terraform/src/test/resources/checks/DisabledLoggingCheck/azurerm_automation_runbook.tf
- iac-extensions/terraform/src/test/resources/checks/DisabledLoggingCheck/azurerm_function_app.tf
- its/ruling/src/test/resources/expected/terraform/terraform-S6258.json
This PR combines the first half of 337. It contains [SONARIAC-338](https://jira.sonarsource.com/browse/SONARIAC-338) and [SONARIAC-339](https://jira.sonarsource.com/browse/SONARIAC-339)
> SONARIAC-337 Rule S6258: Disabling logging is security-sensitive (Azure Part I) 

- .cirrus.yml
- .github/workflows/release.yml
> BUILD-2108 Use Vault

- iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/DockerNodeBuilder.java
- iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/DockerParser.java
- iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/DockerPreprocessor.java
- iac-extensions/docker/src/main/java/org/sonar/iac/docker/plugin/DockerSensor.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/checks/DockerVerifier.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/parser/DockerPreprocessorTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/parser/grammar/DockerLexicalGrammarTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/parser/utils/Assertions.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/DockerTestUtils.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/FileImplTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/InstructionImplTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/MaintainerInstructionImplTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/visitors/DockerHighlightingVisitorTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/visitors/DockerMetricsVisitorTest.java
- iac-extensions/docker/src/test/resources/checks/InstructionFormatCheck/Dockerfile
I'm happy to hear any naming suggestions for my new classes and fields :see_no_evil:
> SONARIAC-531 Preprocess line escaping before parsing a Dockerfile - Process escaped line breaks

- iac-extensions/docker/src/main/java/org/sonar/iac/docker/utils/ArgumentUtils.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/utils/ArgumentUtilsTest.java
This PR simply builds a statefull wrapper around the argument resolving. In the end we could get rid of the utils class in call directly ArgumentResolver. However, I don't want to blow up the PR for now.
> SONARIAC-601 Stack Overflow when resolving variable which directs to itself

- iac-extensions/cloudformation/src/main/java/org/sonar/iac/cloudformation/plugin/CloudformationSensor.java
- iac-extensions/cloudformation/src/test/java/org/sonar/iac/cloudformation/plugin/CloudformationSensorTest.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/plugin/KubernetesSensor.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/plugin/KubernetesSensorTest.java
Fix new line separation on Windows
> SONARIAC-598 Kubernetes & CloudFormation slow check if the file should be scanned for big files

- iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/impl/EnvInstructionImpl.java
- iac-extensions/docker/src/main/java/org/sonar/iac/docker/visitors/DockerSymbolVisitor.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/EnvInstructionImplTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/utils/ArgumentUtilsTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/visitors/DockerSymbolVisitorTest.java
- its/ruling/src/test/resources/expected/docker/docker-S5332.json
- its/ruling/src/test/resources/expected/docker/docker-S6500.json
This reverts commit 147794d8dfb357b0b4de01c5e1f4b852bb3d59f7.
> Revert "SONARIAC-617 Track ENV arguments similar to ARG arguments when resolving variables (#567)"

- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/plugin/KubernetesSensor.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/plugin/KubernetesSensorTest.java
- its/ruling/src/test/resources/expected/kubernetes/kubernetes-S6433.json
It's "Cherry Pick" from the HOTFIX 1.9 branch
> SONARIAC-435 Do not raise parser errors on Helm syntax template directives

- .cirrus.yml
This PR will clean up our CI pipeline as well as provide more power for the ws scan task so it will not fail anymore.
> Improve readability of CI pipeline

- iac-extensions/arm/src/test/java/org/sonar/iac/arm/tree/impl/json/ResourceDeclarationImplTest.java
Supported without code modification since https://sonarsource.atlassian.net/browse/SONARIAC-840, just adding the test case.
> SONARIAC-845 Convert JSON to Minimal ARM AST Model: ARM Parse an array in property in resource declaration

- iac-common/src/main/java/org/sonar/iac/common/extension/ParseException.java
- iac-common/src/test/java/org/sonar/iac/common/extension/ParseExceptionTest.java
- iac-common/src/test/java/org/sonar/iac/common/yaml/YamlSensorTest.java
- iac-extensions/arm/src/main/java/org/sonar/iac/arm/parser/ArmBaseConverter.java
- iac-extensions/arm/src/test/java/org/sonar/iac/arm/parser/ArmParserTest.java
- iac-extensions/arm/src/test/java/org/sonar/iac/arm/tree/impl/json/ParameterDeclarationImplTest.java
- iac-extensions/docker/src/test/java/org/sonar/iac/docker/parser/DockerParserTest.java
> SONARIAC-832 Add Azure Resource Manager Integration Tests

- iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/UnencryptedCloudServicesCheck.java
- iac-extensions/arm/src/test/java/org/sonar/iac/arm/checks/UnencryptedCloudServicesCheckTest.java
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/MultiUnencryptedInfrastructureEncrypted.json
* Implemented part of the rule S6388
* Fixed the message according to the RSPEC
> SONARIAC-916 S6388: Omitting encryptionState or infrastructureEncryption

- iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/UnencryptedCloudServicesCheck.java
- iac-extensions/arm/src/test/java/org/sonar/iac/arm/checks/UnencryptedCloudServicesCheckTest.java
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/AzureArcData_sqlServerInstances_databases.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/Compute_virtualMachineScaleSets.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/Compute_virtualMachines.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/ContainerService_managedClusters.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/HDInsight_clusters.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/HDInsight_clusters_applications.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/Kusto_clusters.json
- iac-extensions/arm/src/test/resources/checks/UnencryptedCloudServicesCheck/SqlVirtualMachine_sqlVirtualMachines.json
Not sure what to do about the code smells.
For resource type, a possible solution would be to define an enum with the associated path and reference them everywhere, but this would add a layer of abstraction when reading the rule.
> SONARIAC-913 S6288: Omitting or setting encryption to false

- iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/ArmCheckList.java
- iac-extensions/arm/src/main/resources/org/sonar/l10n/azureresourcemanager/rules/azureresourcemanager/S1135.html
- iac-extensions/arm/src/main/resources/org/sonar/l10n/azureresourcemanager/rules/azureresourcemanager/S1135.json
- iac-extensions/arm/src/main/resources/org/sonar/l10n/azureresourcemanager/rules/azureresourcemanager/Sonar_way_profile.json
- iac-extensions/arm/src/test/java/org/sonar/iac/arm/checks/ArmCheckListTest.java
- its/ruling/src/test/resources/expected/azureresourcemanager/azureresourcemanager-S1135.json
- its/ruling/src/test/resources/expected/azureresourcemanager/azureresourcemanager-S5332.json
- its/ruling/src/test/resources/expected/azureresourcemanager/azureresourcemanager-S6380.json
- its/ruling/src/test/resources/sources/azureresourcemanager/rules/S1135.bicep
The related RSPEC [PR](https://github.com/SonarSource/rspec/pull/2788) also needs to be reviewed and merged
> SONARIAC-1063 Rule S1135: Track uses of "TODO" tags

- .cirrus.yml
- its/plugin/src/test/java/org/sonarsource/iac/TestBase.java
- its/ruling/src/test/java/org/sonarsource/iac/IacRulingTest.java
- pom.xml
* Update specification for images
* Set sonar scanner version to the latest
> SONARIAC-1076 Use Java 17 to build project

- .cirrus.yml
- .cirrus/Dockerfile-win-build
- .gitattributes
- .gitignore
- pom.xml
- sonar-helm-for-iac/Readme.md
- sonar-helm-for-iac/go.mod
- sonar-helm-for-iac/main.go
- sonar-helm-for-iac/main_test.go
- sonar-helm-for-iac/make.bat
- sonar-helm-for-iac/make.sh
- sonar-helm-for-iac/pom.xml
The first commit contains a make.sh from sonar-go, and the second contains adjustments for our case.
> SONARIAC-1144 Prepare a separate module for Go text template code

- wss-unified-agent.config
The Mend scan is only executed on the master branch so it's hard to verify it on PR level.
> Try to enable Go scan in Mend

- .cirrus.yml
- sonar-helm-for-iac/Dockerfile
- sonar-helm-for-iac/build.gradle.kts
- sonar-helm-for-iac/make.sh
- sonar-iac-plugin/build.gradle.kts
* Change image from eclipse-temurin to golang - we don't use Java in this build; go is pre-installed in golang image
* Make UID of the image user configurable: it's not always 1000
* Remove container after build
> Refactor Dockerfile in sonar-helm-for-iac

- sonar-helm-for-iac/build.gradle.kts
- sonar-helm-for-iac/go.mod
- sonar-helm-for-iac/go.sum
Also added `go.mod` and `go.sum` as inputs for Go build tasks and executed `go mod tidy`
> SONARIAC-1250 Update golang.org/x/crypto to 0.17.0

- iac-extensions/kubernetes/src/main/java/org/sonar/iac/helm/utils/HelmFilesystemUtils.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/helm/utils/HelmFilesystemUtilsTest.java
- sonar-iac-plugin/src/test/java/org/sonar/iac/ArchUnitTest.java
> SONARIAC-1285 Fix aggregation of additional helm files for windows

- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/LocationShifter.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/CapabilitiesCheckTest.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/KubernetesVerifierTest.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/RBACWildcardCheckTest.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/visitors/LocationShifterTest.java
- iac-extensions/kubernetes/src/test/resources/checks/CapabilitiesCheck/CapabilitiesChart/templates/capabilities-pod.yaml
- iac-extensions/kubernetes/src/test/resources/checks/ContainerPrivilegedModeCheck/helm/templates/container_privileged_mode_helm.yaml
- iac-extensions/kubernetes/src/test/resources/checks/CpuLimitCheck/helm/templates/cpu_limit_helm.yaml
- iac-extensions/kubernetes/src/test/resources/checks/EphemeralStorageLimitCheck/helm/templates/ephemeral_storage_limit_helm.yaml
- iac-extensions/kubernetes/src/test/resources/checks/PrivilegeEscalationCheck/PrivilegeChart/templates/privilege-pod.yaml
- iac-extensions/kubernetes/src/test/resources/checks/RBACWildcardCheck/helm/templates/cluster-role.yaml
- its/ruling/src/integrationTest/resources/expected/kubernetes/kubernetes-S6865.json
- sonar-helm-for-iac/Readme.md
- sonar-helm-for-iac/go.work.sum
- sonar-helm-for-iac/src/converters/tree_converter.go
- sonar-helm-for-iac/src/converters/tree_converter_test.go
- sonar-helm-for-iac/src/go.mod
- sonar-helm-for-iac/src/go.sum
- sonar-helm-for-iac/src/main_test.go
Relevant diff: https://github.com/SonarSource/go/compare/src/v1.21.8-4...src/v1.21.8-7
> SONARIAC-1356 Provide precise node lengths in the Go template AST

- iac-extensions/spring-config/src/main/antlr/PropertiesLexer.g4
- iac-extensions/spring-config/src/main/antlr/PropertiesParser.g4
- iac-extensions/spring-config/src/test/java/org/sonar/iac/springconfig/parser/SpringConfigParserTest.java
- iac-extensions/spring-config/src/test/java/org/sonar/iac/springconfig/parser/properties/PropertiesParserBaseVisitorTest.java
- iac-extensions/spring-config/src/test/java/org/sonar/iac/springconfig/parser/properties/SpringConfigPropertiesParserTest.java
Remove dead parsing rule for propertiesFile as WHITESPACE in DEFAULT_MODE is in channel(HIDDEN)
> Cleanup properties grammar, removing dead rule in propertiesFile

- iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/checks/azure/AzureWeakSSLProtocolCheckPart.java
- iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/checks/WeakSSLProtocolCheckTest.java
- iac-extensions/terraform/src/test/resources/checks/WeakSSLProtocolCheck/azure_mysql_server_v3.tf
- iac-extensions/terraform/src/test/resources/checks/WeakSSLProtocolCheck/azure_postgresql_server_v3.tf
- iac-extensions/terraform/src/test/resources/checks/WeakSSLProtocolCheck/azure_storage_account_v3.tf
- its/ruling/src/integrationTest/resources/expected/terraform/terraform-S4423.json
Relevant rspec: https://github.com/SonarSource/rspec/pull/2676
> SONARIAC-1035 S4423 should not report missing property for Azure resources with azurerm >= 3.0

- .cirrus/modules/qa.star
qa_plugin SQ_VERSION:DEV 17 min -> 7 min on CI
> Speedup QA builds

- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/checks/AbstractLimitCheck.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/checks/AbstractRequestCheck.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/checks/AbstractResourceManagementCheck.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/checks/EphemeralStorageLimitCheck.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/checks/MemoryLimitCheck.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/KubernetesCheckContext.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/KubernetesChecksVisitor.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/ProjectContext.java
- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/ProjectContextEnricherVisitor.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/KubernetesVerifier.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/KubernetesVerifierTest.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/MemoryLimitCheckTest.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/visitors/KubernetesChecksVisitorTest.java
- iac-extensions/kubernetes/src/test/resources/checks/MemoryLimitCheck/limit_range.yaml
- iac-extensions/kubernetes/src/test/resources/checks/MemoryLimitCheck/limit_range_cpu.yaml
- iac-extensions/kubernetes/src/test/resources/checks/MemoryLimitCheck/limit_range_default_namespace.yaml
- iac-extensions/kubernetes/src/test/resources/checks/MemoryLimitCheck/memory_limit_deployment_with_global_limit.yaml
- iac-extensions/kubernetes/src/test/resources/checks/MemoryLimitCheck/memory_limit_pod_with_global_limit.yaml
- its/ruling/src/integrationTest/resources/expected/kubernetes_cross_file/kubernetes-S6864.json
Related RSPEC: https://github.com/SonarSource/rspec/pull/4002
> SONARIAC-1204 S6864: Should not raise with LimitRange in the same namespace setting Memory Limit

- iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/checks/CpuRequestCheck.java
- iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/checks/CpuRequestCheckTest.java
- iac-extensions/kubernetes/src/test/resources/checks/CpuRequestCheck/cpu_request_pod.yaml
- iac-extensions/kubernetes/src/test/resources/checks/CpuRequestCheck/cpu_request_pod_with_global_request.yaml
- iac-extensions/kubernetes/src/test/resources/checks/CpuRequestCheck/helm/templates/cpu_request_helm_with_global_request.yaml
- iac-extensions/kubernetes/src/test/resources/checks/CpuRequestCheck/helm/templates/limit_ranges.yaml
- iac-extensions/kubernetes/src/test/resources/checks/CpuRequestCheck/limit_ranges.yaml
RSPEC PR: https://github.com/SonarSource/rspec/pull/4017
> SONARIAC-1299 S6892: Should not raise with LimitRange in the same namespace setting CPU Requests

- .cirrus/modules/build.star
- .cirrus/modules/cache.star
- .cirrus/modules/promote.star
- .cirrus/modules/qa.star
Integrates https://github.com/SonarSource/cirrus-modules/pull/79
> Use the updated version of shared Cirrus library

- iac-extensions/docker/src/main/java/org/sonar/iac/docker/checks/ExecutableNotOwnedByRootCheck.java
- iac-extensions/docker/src/test/resources/checks/ExecutableNotOwnedByRootCheck/add_copy.dockerfile
Follow-up for https://github.com/SonarSource/sonar-iac/pull/1510
> Fix issue message for docker:S6504
