SonarSource/sonar-iac

.cirrus.yml

The WhiteSource scan seems to have [OOM](https://cirrus-ci.com/task/6298251589582848) problems. Let's try to resolve the OOM by increasing the memory up to 2GB.
(Successful run with 2GB https://cirrus-ci.com/task/5414371949019136)

Increase memory for WhiteSource scan task

---

iac-common/pom.xml
iac-extensions/cloudformation/pom.xml
iac-extensions/kubernetes/pom.xml
iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/plugin/KubernetesSensor.java
iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/plugin/KubernetesSensorTest.java
iac-extensions/pom.xml
iac-extensions/terraform/pom.xml
its/plugin/pom.xml
its/pom.xml
its/ruling/pom.xml
pom.xml
sonar-iac-plugin/pom.xml

DO NOT MERGE ON MASTER
Please take into account, that the first 2 commits are already released. The release will be done from this branch and only a cherry-pick of the fix will be on master.

HOTFIX 1.9.2: SONARIAC-435 Do not raise parser errors on Helm syntax template directives

---

.gitmodules

The GitHub repo of the project `terraform-aws-iac/terraform-aws-iam-role` was removed by the maintainer. We have to drop it from the sources of our integration tests.

Drop removed ruling benchmark

---

iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/TreeFactory.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/grammar/DockerGrammar.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/grammar/DockerLexicalConstant.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/grammar/DockerLexicalGrammar.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/api/PortTree.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/impl/PortTreeImpl.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/ExposeTreeImplTest.java

I choose the simple approach of adding another field to handle port + replacing the existing one : `port` -> `portMin` and `portMax`.
In case there is only one port provided -> `portMin == portMax`
Another solution would be to have this in another class `PortRangeTreeImpl`, open to challenge !
I took also the opportunity to fix the related grammar.

SONARIAC-484 Support port range for instruction EXPOSE

---

iac-extensions/docker/src/main/java/org/sonar/iac/docker/parser/grammar/DockerLexicalGrammar.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/UserTreeImplTest.java

Actually, a username can be almost everything except colon, whitespace, and tabulation.
There are only recommendations about usernames. Docker accepts everything except:
```
```
Source: https://www.unix.com/man-page/linux/8/useradd/ (section CAVEATS).

SONARIAC-510 Usernames in the USER instruction can be uppercase

---

iac-extensions/docker/src/main/java/org/sonar/iac/docker/checks/DirectoryCopySourceCheck.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/checks/UnencryptedProtocolCheck.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/tree/impl/AbstractTransferImpl.java
iac-extensions/docker/src/main/java/org/sonar/iac/docker/utils/ArgumentUtils.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/TestUtils.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/api/ArgumentAssert.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/api/ArgumentResolutionAssert.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/AddInstructionImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/CmdInstructionImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/CopyInstructionImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/EntrypointInstructionImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/OnBuildInstructionImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/RunInstructionImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/tree/impl/ShellFormImplTest.java
iac-extensions/docker/src/test/java/org/sonar/iac/docker/utils/ArgumentUtilsTest.java

Sorry for the large PR. I introduced a new assertion class and replaced old ones. 
The PR also solves "[SONARIAC-594](https://sonarsource.atlassian.net/browse/SONARIAC-594) Get rid of SyntaxTokenUtils"
[SONARIAC-594]: https://sonarsource.atlassian.net/browse/SONARIAC-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONARIAC-595 TransferInstruction should relay on Arguments not on SyntaxTokens

---

its/ruling/src/test/java/org/sonarsource/iac/IacRulingTest.java

We can make use of the fail-fast property for our ruling ITs. This way we can already identify issues within checks before merging on the master.

Set fail-fast property for ITs

---

iac-common/src/main/java/org/sonar/iac/common/warnings/AnalysisWarningsWrapper.java
iac-common/src/main/java/org/sonar/iac/common/warnings/DefaultAnalysisWarningsWrapper.java
iac-common/src/main/java/org/sonar/iac/common/warnings/package-info.java
iac-common/src/test/java/org/sonar/iac/common/warnings/DefaultAnalysisWarningsWrapperTest.java
iac-extensions/cloudformation/src/main/java/org/sonar/iac/cloudformation/plugin/CloudformationSensor.java
iac-extensions/cloudformation/src/main/java/org/sonar/iac/cloudformation/reports/CfnLintImporter.java
iac-extensions/cloudformation/src/test/java/org/sonar/iac/cloudformation/plugin/CfnLintImporterTest.java
iac-extensions/cloudformation/src/test/java/org/sonar/iac/cloudformation/plugin/CloudformationSensorTest.java
iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/plugin/TerraformProviders.java
iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/plugin/TerraformProvidersTest.java
iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/plugin/TerraformSensorTest.java
sonar-iac-plugin/src/test/java/org/sonar/plugins/iac/IacPluginTest.java

During the implementation of this ticket, I released, that we lack integration tests for the CfnLint report import in the Cloudformation extension as well as for the configuration of an AWS provider version in the Terraform extension. To address these missing ITs, I've created:
* [SONARIAC-661](https://sonarsource.atlassian.net/browse/SONARIAC-661) Add integration test for CfnLint report import
* [SONARIAC-662](https://sonarsource.atlassian.net/browse/SONARIAC-662) Add property integration test for invalid AWS provider versions
Which should be added soon, but are no blockers for a SonarLint integration.
[SONARIAC-661]: https://sonarsource.atlassian.net/browse/SONARIAC-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SONARIAC-662]: …

SONARIAC-636  Add wrapper to AnalysisWarnings to allow sensor initialization in SonarLint context

---

iac-extensions/terraform/src/test/java/org/sonar/iac/terraform/plugin/TerraformSensorTest.java

@nils-werner-sonarsource should fix :red_circle:  master.

Fix missing import in test

---

iac-extensions/cloudformation/src/main/java/org/sonar/iac/cloudformation/plugin/CloudformationSensor.java
iac-extensions/cloudformation/src/main/java/org/sonar/iac/cloudformation/reports/CfnLintImporter.java
iac-extensions/cloudformation/src/test/java/org/sonar/iac/cloudformation/plugin/CfnLintImporterTest.java
iac-extensions/cloudformation/src/test/resources/cfn-lint/invalidPathMoreThanTwo.json
iac-extensions/cloudformation/src/test/resources/cfn-lint/invalidPathTwo.json

This is how the warning would look in the UI now:
The part that was added in this PR is basically the `"Some file paths could not be resolved: doesNotExist.yaml, a/b/doesNotExistToo.yaml, ..."` to help the user identify the problem. 
Happy to give more context to the change if needed. 
Not sure why the SonarCloud bot is not commenting on this PR anymore. The analysis is green though: https://github.com/SonarSource/sonar-iac/pull/616/checks?check_run_id=12089634838

SONARIAC-182 Cfn-lint import error log should convey the reason

---

pom.xml

As we set an unreleased version we now fail to build the plugin. After 2 weeks the unreleased artifact will be removed. This will not affect the released version of sonar-iac but to have nightly builds of sonar-iac we have to set the used version to a released one which will not be deleted.

Set released sonarlint-core version for integration test

---

iac-extensions/arm/src/main/java/org/sonar/iac/arm/parser/ArmParser.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/ArmTree.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/ArrayExpression.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/Expression.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/ObjectExpression.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/Property.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/PropertyValue.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/SimpleProperty.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/ArmHelper.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/ArrayExpressionImpl.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/ObjectExpressionImpl.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/OutputDeclarationImpl.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/ParameterDeclarationImpl.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/PropertyImpl.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/ResourceDeclarationImpl.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/SimplePropertyImpl.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/parser/json/OutputDeclarationTest.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/parser/json/ResourceDeclarationTest.java

Changed a bit the approach regarding `Property`:
- `Property` as it was has been renamed to `SimpleProperty`: the key is an `Identifier` and the value is always an `Expression`
- Created a `PropertyValue` interface, with three implementations:
- `Expression`, to represent simple value such as `"string"` or `5`
- `ArrayExpression`, to represent a typical array such as `["value1", "value2"]`, where each entry is a `PropertyValue` also
- `ObjectExpression`, which is an object like `{"key":"value"}`, represented as a `List<Property>` and some methods to use it as a `Map`
- `Property` still has `Identifier` as a key, but the value is now a `PropertyValue`
Added some useful methods regarding those changes, like a way to extract and/or convert elements to `SimpleProperty`, which are mainly used …

SONARIAC-840 Convert JSON to Minimal ARM AST Model: Improve Property to support array and object

---

iac-common/src/main/java/org/sonar/iac/common/dsl/CommonPropertySymbol.java
iac-common/src/main/java/org/sonar/iac/common/dsl/Symbol.java
iac-common/src/test/java/org/sonar/iac/common/dsl/CommonPropertySymbolTest.java
iac-common/src/test/java/org/sonar/iac/common/dsl/SymbolTest.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/symbols/MapSymbol.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/symbols/ObjectSymbol.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/symbols/PropertySymbol.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/symbols/ResourceSymbol.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/ArmTestUtils.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/symbols/MapSymbolTest.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/symbols/ObjectSymbolTest.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/symbols/PropertySymbolTest.java
iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/AttributeSymbol.java
iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/BlockSymbol.java
iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/ListSymbol.java
iac-extensions/terraform/src/main/java/org/sonar/iac/terraform/symbols/ReferenceSymbol.java

Removed the MapSymbol from the common package. It does not provide any value but only more complexity. Sorry for the number of files. However, it should not introduce more logic.

SONARIAC-892 Build an ARM Domain Specific Language to simplify rule implementation (Property & Object symbol)

---

iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/ClearTextProtocolsCheck.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/LogRetentionCheck.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/ShortBackupRetentionCheck.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/checks/utils/CheckUtils.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/api/NumericLiteral.java
iac-extensions/arm/src/main/java/org/sonar/iac/arm/tree/impl/json/NumericLiteralImpl.java
iac-extensions/arm/src/test/java/org/sonar/iac/arm/checks/ShortBackupRetentionCheckTest.java
iac-extensions/arm/src/test/resources/checks/ShortBackupRetentionCheck/Microsoft.RecoveryServices_vaults.json
iac-extensions/arm/src/test/resources/checks/ShortBackupRetentionCheck/Microsoft.RecoveryServices_vaults_custom_400.json

This PR also update our model to use a double instead of a float to handle NumericLiteral.
I did it this way because otherwise, it raises a Bug in Sonar when I perform multiply on those numbers.

SONARIAC-813 Rule S6364: ARM Defining a short backup retention duration is security-sensitive (JSON) - Microsoft.RecoveryServices/vaults

---

.cirrus.yml

Any task calling `source cirrus-env <TASK_TYPE>` with `TASK_TYPE!=BUILD*` must depend on the task calling `source cirrus-env BUILD`.
If you want to parallelize the build and the scan tasks, then you have to introduce a common root task to call `source cirrus-env BUILD` first, and then change the `<TASK_TYPE>` of the build task.
See https://github.com/SonarSource/re-ci-images/blob/master/docker/bin/cirrus-env#L24

BUILD-3415 tasks must depend on build

---

.cirrus.yml
sonar-helm-for-iac/make.sh
sonar-helm-for-iac/pom.xml

* Add two additional tasks that build Darwin and Windows artifacts inside `golang-crosscompile` containers and upload them as Cirrus artifacts
* Download these artifacts as part of build task; Linux binary is still being built as part of Maven build
* Change go buildmode to `c-shared`
* In `make.sh`, assume `GOOS` is unset on a developer machine (only set by `go` executable)

SONARIAC-1169 Set up multi-architecture build on Cirrus CI

---

iac-extensions/kubernetes/src/main/java/org/sonar/iac/helm/LineNumberCommentRemover.java
iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/plugin/KubernetesParser.java
iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/CommentLocationVisitor.java
iac-extensions/kubernetes/src/main/java/org/sonar/iac/kubernetes/visitors/LocationShifter.java
iac-extensions/kubernetes/src/test/java/org/sonar/iac/helm/LineNumberCommentRemoverTest.java
iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/plugin/KubernetesParserTest.java
iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/plugin/KubernetesSensorTest.java
iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/visitors/LocationShifterTest.java
its/ruling/src/integrationTest/resources/expected/kubernetes/kubernetes-S2260.json
its/ruling/src/integrationTest/resources/expected/kubernetes/kubernetes-S5849.json
its/ruling/src/integrationTest/resources/expected/kubernetes/kubernetes-S6864.json
its/ruling/src/integrationTest/resources/expected/kubernetes/kubernetes-S6869.json
its/ruling/src/integrationTest/resources/sources/kubernetes/helm/corner-cases/templates/multiline-string.yaml

When `CommentLocationVisitor.visitComment()` is "deactivated", the ruling tests are also green. But removing this code will be in the scope of a separate ticket: SONARIAC-1277

SONARIAC-1271 Should not fail parsing unquoted text

---

.cirrus.yml

Reduces pure Windows build time from 8:20 to 4:30. That reduces the CI time from ~15 min to 11 min

Use a more powerful machine for Windows builds

---

build-logic/src/main/kotlin/org.sonarsource.iac.code-style-convention.gradle.kts
iac-common/src/main/java/org/sonar/iac/common/api/tree/impl/SeparatedListImpl.java
iac-common/src/main/java/org/sonar/iac/common/yaml/tree/YamlTreeMetadata.java

Update of sonar-formatter to version 23 so that records format are specified.
As discussed, `Blowdryer.immutableUrl` should point to an immutable file, as it will never be checked for updates.

Update sonar-formatter to version 23

---

iac-extensions/spring-config/src/main/antlr/PropertiesLexer.g4
iac-extensions/spring-config/src/test/java/org/sonar/iac/springconfig/parser/properties/PropertiesParserBaseVisitorTest.java

This small improvement mitigates log entries to standard error by ANTLR4.
It was caused by a single key without the value after key value pair. In KEY_MODE the ANTRL4 was unable to recognize \n as a new line and print into standard err the following message: line 2:4 token recognition error at '\n'
This PR fixes grammar, reformats lexer rules and validates if standard error is empty

Support entries with a single key in properties grammar

---

.cirrus/modules/build.star

Funnily, we can see in th `STARLARK.md` file in **Task definitions** chapter that the example code provided is the one about the definition of `sca_scan_task` and has the property `"only_if": is_main_branch()`.
Was it changed at some point for some reason?

Change sca_scan condition to only run on main branch.

---

iac-common/src/main/java/org/sonar/iac/common/extension/IacSensor.java
iac-common/src/main/java/org/sonar/iac/common/extension/analyzer/AbstractAnalyzer.java
iac-common/src/main/java/org/sonar/iac/common/extension/analyzer/Analyzer.java
iac-common/src/main/java/org/sonar/iac/common/extension/analyzer/CrossFileAnalyzer.java
iac-common/src/main/java/org/sonar/iac/common/extension/analyzer/SingleFileAnalyzer.java
iac-common/src/test/java/org/sonar/iac/common/extension/analyzer/AbstractAnalyzerTest.java
iac-common/src/test/java/org/sonar/iac/common/extension/analyzer/CrossFileAnalyzerTest.java
iac-common/src/test/java/org/sonar/iac/common/extension/analyzer/SingleFileAnalyzerTest.java
iac-extensions/kubernetes/src/test/java/org/sonar/iac/kubernetes/plugin/KubernetesSensorTest.java

Proposed solution: move the ProgressReport responsibility to the analyzers, as we need different behavior between `SingleFileAnalyzer` and `CrossFileAnalyzer`.

SONARIAC-1511 Change the usage of ProgressReport to do proper reporting in cross file analysis
